### ISSUE TITLE
GPL v3 License is unfriendly, MIT or BSD is preferred

### ISSUE THREAD

**Issue by forest520** [wenmin-wu/jupyter-tabnine#14]
As we know, most of the machine learning open source projects are BSD or MIT license, such as Jupyter, tabnine-vscode, Tensorflow, scikit-learn, etc. GPL is rarely used since it has too many restrictions: [https://www.quora.com/What-are-the-most-restrictive-business-unfriendly-open-source-licenses](https://www.quora.com/What-are-the-most-restrictive-business-unfriendly-open-source-licenses)

So I suggest changing the license from GPL v3 into [BSD](https://opensource.org/licenses/BSD-3-Clause) or [MIT](https://opensource.org/licenses/MIT). Thanks.

**Comment by wenmin-wu** [comment]
I'm not familiar with these licenses,  just randomly choose one. I'm going to change to **MIT** thanks for suggestion.
