### ISSUE TITLE
How can I install it on Anaconda Jupyter

### ISSUE THREAD

**Issue by shinokada** [wenmin-wu/jupyter-tabnine#22]
Could you add the installation for anaconda in the README, please?

**Comment by wenmin-wu** [comment]
You can still install with `pip` in anaconda environment.

**Comment by BothOfUsTogether2** [comment]
author doesn't seem to add instructions on how to install using Anaconda...


and unfortunately, I don't know how to send pull requests..

if you encounter this problem on README.md
the steps for installing tabnine is:
1. clone the repo `git clone https://github.com/wenmin-wu/jupyter-tabnine`
2. install it using anaconda' python `~/anaconda3/bin/python3.7 setup.py install`
