### ISSUE TITLE
INFO on the terminal after installation

### ISSUE THREAD

**Issue by shinokada** [wenmin-wu/jupyter-tabnine#23]
After installation, I restarted three times, but I still get the following INFO.
Is there any way to remove this?

```
[INFO 2020-02-10 07:14:56.509 TabNine]:  install dir: /Users/shinokada/virtualenvs/jupyter/lib/python3.7/site-packages/jupyter_tabnine
[INFO 2020-02-10 07:14:56.510 TabNine]: TabNine binary already exists in /Users/shinokada/virtualenvs/jupyter/lib/python3.7/site-packages/jupyter_tabnine/binaries/2.2.2/x86_64-apple-darwin/TabNine ignore downloading
```

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/147320/74111083-2f2fcb00-4bd5-11ea-9a2a-d70978d3411c.png">

**Comment by wenmin-wu** [comment]
You can just ignore this. These logs just tell you the TabNine binary had downloaded successfully.
