### ISSUE TITLE
No connection to internal server in console, error 500, Jupyter-Tabnine not working on Mac Chrome, Python3

### ISSUE THREAD

**Issue by capnahab** [wenmin-wu/jupyter-tabnine#24]
Here is my Chrome output. I am using jupyter notebook , Python 3 and MacosX Catalina.

`Loading` extension: contrib_nbextensions_help_item/main
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:34748 Loading extension: execute_time/ExecuteTime
ExecuteTime.js?v=20200217233217:55 [ExecuteTime] patching CodeCell.prototype.get_callbacks
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:34748 Loading extension: jupyter_tabnine/main
main.js?v=20200217233217:519 [nbextensions/jupyter_tabnine/main] continuous autocompletion on
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:34748 Loading extension: toc2/main
main.js?v=20200217233217:188 [toc2] Notebook fully loaded -- toc2 initialized 
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:47784 Kernel: kernel_connected (e961c3f7-9b2d-48bf-a2eb-5e481158e013)
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:47784 Kernel: kernel_ready (e961c3f7-9b2d-48bf-a2eb-5e481158e013)
main.js?v=20200217233217:482 [nbextensions/jupyter_tabnine/main]  new base completer
main.js?v=20200217233217:487 [nbextensions/jupyter_tabnine/main]  new deep completer
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:46439 Object
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:46439 Object
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:46439 Object
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:46439 Object
main.js?v=20200217233217:504 [nbextensions/jupyter_tabnine/main]  call deep completer....
:8888/tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22filename%22%3A%22Jupyter%2Fmisc%2FExcelWr.py%22%2C%22before%22%3A%22%23If%20passing%20an%20existing%20ExcelWriter%20object%2C%20then%20the%20sheet%20will%20be%20added%20to%20the%20existing%20workbook.%20This%20can%20be%20used%20to%20%23save%20different%20DataFrames%20to%20one%20workbook%3A%5Cn%23%3E%20writer%20%3D%20pd.ExcelWriter(%27output.xlsx%27)%5Cn%23%3E%20df1.to_excel(writer%2C%27Sheet1%27)%5Cn%23%3E%20df2.to_excel(writer%2C%27Sheet2%27)%5Cn%23%3E%20writer.save()%5Cnimport%20pandas%20%22%2C%22after%22%3A%22%5Cnwriter%20%3D%20pd.ExcelWriter(%2713_14.xlsx%27%2C%20engine%3D%27xlsxwriter%27)%5Cnwriter.save()%5Cnimport%20pandas%20as%20pd%5Cn%23%20dataframe%20Name%20and%20Age%20columns%5Cnpd.read_csv(%27%2FUsers%2Fnicholasphillips%2FDesktop%2FND%2Fbase_data%2F2014_2013.csv%27)%5Cn%23%20Create%20a%20Pandas%20Excel%20writer%20using%20XlsxWriter%20as%20the%20engine.%5Cn%23%23writer%20%3D%20pd.ExcelWriter(%2713_14.xlsx%27%2C%20engine%3D%27xlsxwriter%27)%5Cn%23%20Convert%20the%20dataframe%20to%20an%20XlsxWriter%20Excel%20object.%5Cn%23df.to_excel(writer%2C%20sheet_name%3D%27Sheet1%27%2C%20index%3DFalse)%5Cn%23%20Close%20the%20Pandas%20Excel%20writer%20and%20output%20the%20Excel%20file.%5Cn%23writer.save()%5Cndf1%20%3D%20pd.read_csv(%27%2FUsers%2Fnicholasphillips%2FDesktop%2FND%2Fbase_data%2F2014_2013.csv%27)%5Cnwriter%20%3D%20pd.ExcelWriter(%2713_14.xlsx%27%2C%20engine%3D%27xlsxwriter%27)%5Cndf1.to_excel(writer%2C%20sheet_name%3D%2713_14%27%2C%20index%3DFalse)%5Cnwriter.save()%22%2C%22region_includes_beginning%22%3Atrue%2C%22region_includes_end%22%3Atrue%2C%22max_num_results%22%3A10%7D%7D%7D:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.js?v=20200217233217:123 [nbextensions/jupyter_tabnine/main]  get error:  Object
2main.js?v=20200217233217:147 [nbextensions/jupyter_tabnine/main] complete is visible, ignore by just return
DevTools failed to parse SourceMap: http://localhost:8888/static/notebook/js/main.min.js.map`

**Comment by wenmin-wu** [comment]
Hi @capnahab , seems it's not the problem of jupyter-tabnine but a problem of your jupyter environment. I developed this project on MacOS with Chrome and Python3.
