### ISSUE TITLE
Downloading tabnine binary after installing: Permission denied

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [wenmin-wu/jupyter-tabnine#25]
I have successfully installed TabNine, but the extension fails to download the binary files after starting the notebook:

> [INFO 2020-03-14 16:11:04.407 TabNine]:  install dir: /usr/local/lib/python3.6/dist-packages/jupyter_tabnine
> [INFO 2020-03-14 16:11:04.464 TabNineDownloader]: Begin to download TabNine Binary from https://update.tabnine.com/2.5.1/x86_64-unknown-linux-gnu/TabNine
> [ERROR 2020-03-14 16:11:04.465 TabNineDownloader]: Download failed, error: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/binaries'

I have tried to manually download the binary file from the link, place it inside the folder and restart jupyter but I then get a error when acessing the file:

> [INFO 2020-03-14 16:23:16.306 TabNine]:  install dir: /usr/local/lib/python3.6/dist-packages/jupyter_tabnine
> [W 16:23:16.307 NotebookApp] Error loading server extension jupyter_tabnine
>     Traceback (most recent call last):
>       File "/home/bcoelho/.local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1346, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/__init__.py", line 29, in load_jupyter_server_extension
>         tabnine = TabNine()
>       File "/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/tabnine.py", line 73, in __init__
>         self.download_if_needed()
>       File "/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/tabnine.py", line 127, in download_if_needed
>         os.chmod(tabnine_path, 0o755)
>     PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/binaries/2.5.1/x86_64-unknown-linux-gnu/TabNine'

Is there any way to specify a install directory for example to fix this?

**Comment by BothOfUsTogether2** [comment]
i don't have this issue and im using anaconda3. I think you should look for the permissions of the file by running ls or stat:
'/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/binaries/2.5.1/x86_64-unknown-linux-gnu/TabNine'

the resolution might be adding exec flag to the binary running chmod, like following:
`chmod +x '/usr/local/lib/python3.6/dist-packages/jupyter_tabnine/binaries/2.5.1/x86_64-unknown-linux-gnu/TabNine'`

I added this could be help: https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied

**Comment by wenmin-wu** [comment]
@BrunoGomesCoelho , try this
```
pip3 install jupyter-tabnine --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```
The package will be installed under the user's dir.
