### ISSUE TITLE
auto completion is not working well

### ISSUE THREAD

**Issue by BothOfUsTogether2** [wenmin-wu/jupyter-tabnine#28]
hello,
the tabnine seems to work but the python-language-server doesn't work.
I'm using anaconda3.

I've tried to install pyls but it doesn't install it. with error: 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyls

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

the installation of python-language-server works but that didn't do anything inside jupyter. I tried to install that repo from the source but that didn't help either.

Is there any fix for this issue please?

PS: I think that would be great if we can add that package to https://github.com/wenmin-wu/jupyter-tabnine/blob/master/setup.py#L20 so it won't display the error later

**Comment by wenmin-wu** [comment]
Hi @BothOfUsTogether2 , I guess you are familiar with JavaScript. You can refer this https://github.com/wenmin-wu/jupyter-tabnine/blob/master/DEBUG.md for debugging. Can add the package to `setup.py`. Let me fix this

**Comment by BothOfUsTogether2** [comment]
![image](https://user-images.githubusercontent.com/52379406/77720712-c6bc7200-6ff9-11ea-9d69-c284f6c0c979.png)

**Comment by BothOfUsTogether2** [comment]
If I type the variable without dot it shows this message:

![image](https://user-images.githubusercontent.com/52379406/77720808-071bf000-6ffa-11ea-9392-cd4f72d6cb33.png)

**Comment by BothOfUsTogether2** [comment]
still doesn't autocomplete after upgrading version
