### ISSUE TITLE
jupyter-tabnine doesnt work at all after installation

### ISSUE THREAD

**Issue by analaarun** [wenmin-wu/jupyter-tabnine#33]
Installed jupyter-tabnine as given in instruction, but getting error on launching jupyter notebook. Also default intelisense stopped working.
![image](https://user-images.githubusercontent.com/15939650/79137176-dc8aaf00-7dcf-11ea-90cb-57fff1b9cdfd.png)

**Comment by wenmin-wu** [comment]
For your case, I think we didn't correctly configure the server extension. Please issue `jupyter serverextension enable --py jupyter_tabnine` and restart

**Comment by wenmin-wu** [comment]
I have update the README.md, always try to install and configure this plugin by issuing following commands first:
```
pip3 install jupyter-tabnine --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```
