### ISSUE TITLE
I followed the installation steps but it did not work.

### ISSUE THREAD

**Issue by sidhantagar** [wenmin-wu/jupyter-tabnine#35]
404 GET /tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22filename%22%3A%22Untitled.py%22%2C%22before%22%3A%22impo%22%2C%22after%22%3A%22%22%2C%22region_includes_beginning%22%3Atrue%2C%22region_includes_end%22%3Atrue%2C%22max_num_results%22%3A10%7D%7D%7D (::1) 6.05ms referer=None

I am getting this error  in the console log.

Also i tried running jupyter nbextension list

Known nbextensions:
  config dir: C:\Users\sidha\.jupyter\nbconfig
    notebook section
      jupyter_tabnine/main enabled
      - Validating: ok
  config dir: c:\users\sidha\appdata\local\programs\python\python38-32\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Comment by wenmin-wu** [comment]
This plugin not only contains a nbextension but also a server extension. Since the server cannot be found in your case, I guess you didn't enable the server, please install and configure with the following commands, the last one is to enable the server extension.
```
pip3 install jupyter-tabnine --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```
