### ISSUE TITLE
TabNine::sem message after install

### ISSUE THREAD

**Issue by achtungmike** [wenmin-wu/jupyter-tabnine#5]
After installation I am getting a warning message about TabNine::sem.  How do I enable TabNine::sem or disable this message in your extension?  The commands the warning message give do not work from inside Jupyter.

![tab_nine](https://user-images.githubusercontent.com/31513230/66484178-83367180-ea74-11e9-91c9-7e2027824174.png)

Thank you!

**Comment by wenmin-wu** [comment]
Just type `TabNine::sem` in Jupyter Notebook cell. And it will start to download the python language server.

**Comment by achtungmike** [comment]
I get an invalid syntax error.

![Capture](https://user-images.githubusercontent.com/31513230/66486399-87648e00-ea78-11e9-828b-a4b55dee6a6c.PNG)

**Comment by wenmin-wu** [comment]
@achtungmike don't try to execute this cell. Just type it, and it will trigger the downloading of the python language server automatically.  You can press `Tab` to get the downloading information. After that, you can delete this line(`TabNine::sem`). I will fix this problem by downloading the language server at start, then users won't come across with this warning.
