### ISSUE TITLE
GET http://127.0.0.1:8888/tabnine?data=BIG_STRING 404 (Not Found)

### ISSUE THREAD

**Issue by Maulorian** [wenmin-wu/jupyter-tabnine#57]
I'm getting this error when trying to use your plugin:
<img width="1532" alt="Screenshot 2020-11-12 at 15 22 03" src="https://user-images.githubusercontent.com/25705704/98945178-70e9fb00-24f2-11eb-8eda-01128feb6104.png">

**Comment by wenmin-wu** [comment]
Hi @Maulorian, this issue is fixed in this [commit](https://github.com/wenmin-wu/jupyter-tabnine/commit/f1615b54a2662f8c80e2ead225c40cf298f68e2c)

Please reinstall with the following commands:
```Bash
pip install https://github.com/wenmin-wu/jupyter-tabnine/archive/master.zip --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```
I'm going to release the new version to `pypi` after several days of using.

**Comment by wenmin-wu** [comment]
The newest version is available on [pypi](https://pypi.org/project/jupyter-tabnine/), you can install with `pip install jupyter-tabnine`
