### ISSUE TITLE
TabNine::sem not working 

### ISSUE THREAD

**Issue by bonysimon007** [wenmin-wu/jupyter-tabnine#6]
I tried to enable TabNine::sem but it returned error saying command failed is pip install python-language-server. I installed the package manually as well. But still not working. 

Also, is it possible to use this module for jupyter lab?-

**Comment by wenmin-wu** [comment]
- I'm working on a version to install python language server by default. In this way, you won't need to install the server manually by typing `TabNine::sem`. Actually, I won't see the warning any more. 

- Yes, I will make it possible to be used in jupyter lab.

will ping you when I finish these.
