### ISSUE TITLE
Support for jupyter notebooks on VSCode

### ISSUE THREAD

**Issue by jaimeperezsanchez** [wenmin-wu/jupyter-tabnine#8]
Hi, since native support for jupyter notebooks has recently been announced on VSCode:
Is there any way for Tabnine to work in these files?
Is their support planned?

Thank you!

**Comment by wenmin-wu** [comment]
As far as I know, when coding on VSCode there are many plugins providing auto-completion like `IntelliSense `. You can also install TabNine from plugins market of `VSCode`.
